#!/bin/sh
display_help() {
    echo "Usage: $0 [profile_name|--clear|--help] [--export]"
    echo
    echo "Arguments:"
    echo "  profile_name   Name of the AWS profile to use."
    echo "  --clear        Clear all AWS environment variables."
    echo "  --help         Display this help information."
    echo "  --export       Export AWS environment variables for the specified profile."
    echo
    echo "Example:"
    echo "  $0 myprofile --export"
    echo "  $0 --clear"
}

clear() {
    unset AWS_ACCESS_KEY_ID
    unset AWS_SECRET_ACCESS_KEY
    unset AWS_SESSION_TOKEN
    unset AWS_DEFAULT_REGION
    unset AWS_PROFILE
    export AWS_ACCESS_KEY_ID
    export AWS_SECRET_ACCESS_KEY
    export AWS_SESSION_TOKEN
    export AWS_SECRET_KEY
    export AWS_PROFILE
}

if [ -z "$1" ] || [ "$1" = "--help" ]; then
    display_help
    exit 0
fi

if [ "$1" = "clear" ]; then
    echo "Clearing AWS environment variables..."
    clear
    echo "AWS environment variables cleared."
    exit 0
fi

if ! aws sts get-caller-identity --profile=$1 >/dev/null 2>&1; then
    echo "AWS credentials are invalid or expired."
    aws sso login --profile=$1
else
    echo "Done"
fi


export AWS_PROFILE=$1
echo "AWS Profile set to $1"

if [ "$2" = "--export" ]; then
    #eval "$(aws configure export-credentials --profile $1 --format env)"
    eval "$(aws configure export-credentials --profile $1 --format env)"
    echo "AWS environment variables exported."
    export AWS_ACCESS_KEY_ID
    export AWS_SECRET_ACCESS_KEY
    export AWS_SESSION_TOKEN
    export AWS_SECRET_KEY
fi

