#!/bin/sh
set -o errexit -o pipefail -o noclobber -o nounset
display_help() {
    echo "Usage: $0 [profile_name] [--clear] [--help] [--export]"
    echo
    echo "Arguments:"
    echo "  profile_name   Name of the AWS profile to use."
    echo "  --clear        Clear all AWS environment variables."
    echo "  --help         Display this help information."
    echo "  --export       Export AWS environment variables for the specified profile."
    echo
    echo "Example:"
    echo "  $0 myprofile --export"
    echo "  $0 --clear"
}

clear() {
    unset AWS_ACCESS_KEY_ID
    unset AWS_SECRET_ACCESS_KEY
    unset AWS_SESSION_TOKEN
    unset AWS_DEFAULT_REGION
    unset AWS_PROFILE
    export AWS_ACCESS_KEY_ID
    export AWS_SECRET_ACCESS_KEY
    export AWS_SESSION_TOKEN
    export AWS_SECRET_KEY
    export AWS_PROFILE
}

profile_list=$(aws configure list-profiles)
profile_array=()
for i in $profile_list; do profile_array+=($i) ; done


CURRENT_PROFILE="${PROFILE-}"
SHOULD_EXPORT=false
for arg in "$@"; do
    if [ "$arg" = "--help" ]; then
        display_help
        exit 0
        elif [ "$arg" = "--clear" ]; then
        clear
        echo "AWS environment variables cleared."
        exit 0
        elif [ "$arg" = "--export" ]; then
        SHOULD_EXPORT=true
    else
        PROFILE=$arg
    fi
done
clear
if [ -z "${PROFILE-}" ]; then
    echo -e "\033[1mSelect profiles\033[0m"
    echo "----------------"
    select profile in "${profile_array[@]}"; do
        if [[ -n $profile ]]; then
            echo "You selected $profile"
            PROFILE=$profile
            break
        else
            echo "Invalid choice. Please try again."
        fi
    done
    
fi

if [[ ! " ${profile_array[@]} " =~ " ${PROFILE-} " ]]; then
    if [ -z "${PROFILE-}" ]; then
        echo "No profile specified."
    else
        echo "Profile $PROFILE does not exist."
    fi
    exit 1
fi


if ! aws sts get-caller-identity --profile=$PROFILE >/dev/null 2>&1; then
    echo "AWS credentials are invalid or expired."
    aws sso login --profile=$PROFILE
else
    echo "Done"
fi


export AWS_PROFILE=$PROFILE
echo "AWS Profile set to $PROFILE"

if [ "$SHOULD_EXPORT" = "true" ]; then
    eval "$(aws configure export-credentials --profile $PROFILE --format env)"
    echo "AWS environment variables exported."
    export AWS_ACCESS_KEY_ID
    export AWS_SECRET_ACCESS_KEY
    export AWS_SESSION_TOKEN
    export AWS_SECRET_KEY
fi

